-- Generated by the Organizer Library (10/14/17 14:57:57)
return {
    [1]={
        ["log_name"]="chaac belt", 
        ["id"]=28450, 
        ["name"]="chaac belt", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="repulse mantle", 
        ["id"]=28639, 
        ["name"]="repulse mantle", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="moonbeam necklace", 
        ["id"]=26036, 
        ["name"]="moonbeam necklace", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="goading belt", 
        ["id"]=11729, 
        ["name"]="goading belt", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="shadow mantle", 
        ["id"]=13658, 
        ["name"]="shadow mantle", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="eschan stone", 
        ["id"]=28415, 
        ["name"]="eschan stone", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="loricate torque +1", 
        ["id"]=26002, 
        ["name"]="loricate torque +1", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="moonbeam ring", 
        ["id"]=26189, 
        ["name"]="moonbeam ring", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="moonbeam ring", 
        ["id"]=26189, 
        ["name"]="moonbeam ring", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="colossus's torque", 
        ["id"]=11590, 
        ["name"]="colossus's torque", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="asperity necklace", 
        ["id"]=28402, 
        ["name"]="asperity necklace", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="moonbeam cape", 
        ["id"]=26268, 
        ["name"]="moonbeam cape", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="fucho-no-obi", 
        ["id"]=28452, 
        ["name"]="fucho-no-obi", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="nierenschutz", 
        ["id"]=11730, 
        ["name"]="nierenschutz", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="fotia gorget", 
        ["id"]=27510, 
        ["name"]="fotia gorget", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="atheling mantle", 
        ["id"]=16260, 
        ["name"]="atheling mantle", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="toro cape", 
        ["id"]=28615, 
        ["name"]="toro cape", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="flume belt +1", 
        ["id"]=28437, 
        ["name"]="flume belt +1", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="olympus sash", 
        ["id"]=10821, 
        ["name"]="olympus sash", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="siegel sash", 
        ["id"]=15960, 
        ["name"]="siegel sash", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="letalis mantle", 
        ["id"]=11007, 
        ["name"]="letalis mantle", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="asklepian belt", 
        ["id"]=26327, 
        ["name"]="asklepian belt", 
        ["count"]=1
    }
}