-- Generated by the Organizer Library (10/14/17 14:57:57)
return {
    [1]={
        ["log_name"]="arvina ringlet +1", 
        ["id"]=28536, 
        ["name"]="arvina ringlet +1", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="cessance earring", 
        ["id"]=27541, 
        ["name"]="cessance earring", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="loquacious earring", 
        ["id"]=14812, 
        ["name"]="loquac. earring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="apeile ring +1", 
        ["id"]=27561, 
        ["name"]="apeile ring +1", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="phalaina locket", 
        ["id"]=10960, 
        ["name"]="phalaina locket", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="infused earring", 
        ["id"]=28475, 
        ["name"]="infused earring", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="defending ring", 
        ["id"]=13566, 
        ["name"]="defending ring", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="paguroidea ring", 
        ["id"]=10753, 
        ["name"]="paguroidea ring", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="sanctity necklace", 
        ["id"]=26023, 
        ["name"]="sanctity necklace", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="acumen ring", 
        ["id"]=28554, 
        ["name"]="acumen ring", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="moonshade earring", 
        ["count"]=1, 
        ["id"]=11697, 
        ["name"]="moonshade earring", 
        ["augments"]={
            [1]="Accuracy+4", 
            [2]="TP Bonus +25"
        }
    }, 
    [12]={
        ["log_name"]="sheltered ring", 
        ["id"]=10764, 
        ["name"]="sheltered ring", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="apeile ring", 
        ["id"]=27560, 
        ["name"]="apeile ring", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="telos earring", 
        ["id"]=27545, 
        ["name"]="telos earring", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="nourishing earring +1", 
        ["id"]=28485, 
        ["name"]="nourish. earring +1", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="rajas ring", 
        ["id"]=15543, 
        ["name"]="rajas ring", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="dudgeon earring", 
        ["id"]=28522, 
        ["name"]="dudgeon earring", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="mendicant's earring", 
        ["id"]=28474, 
        ["name"]="mendi. earring", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="asklepian ring", 
        ["id"]=10787, 
        ["name"]="asklepian ring", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="steelflash earring", 
        ["id"]=28520, 
        ["name"]="steelflash earring", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="k'ayres ring", 
        ["id"]=28579, 
        ["name"]="k'ayres ring", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="bladeborn earring", 
        ["id"]=28521, 
        ["name"]="bladeborn earring", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="brutal earring", 
        ["id"]=14813, 
        ["name"]="brutal earring", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="heartseeker earring", 
        ["id"]=28523, 
        ["name"]="heartseeker earring", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="incanter's torque", 
        ["id"]=26016, 
        ["name"]="incanter's torque", 
        ["count"]=1
    }, 
    [26]={
        ["log_name"]="enchanter earring +1", 
        ["id"]=28494, 
        ["name"]="enchntr. earring +1", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="globidonta ring", 
        ["id"]=28539, 
        ["name"]="globidonta ring", 
        ["count"]=1
    }, 
    [28]={
        ["log_name"]="knightly earring", 
        ["id"]=14758, 
        ["name"]="knightly earring", 
        ["count"]=1
    }, 
    [29]={
        ["log_name"]="prolix ring", 
        ["id"]=10752, 
        ["name"]="prolix ring", 
        ["count"]=1
    }, 
    [30]={
        ["log_name"]="beatific earring", 
        ["id"]=10298, 
        ["name"]="beatific earring", 
        ["count"]=1
    }, 
    [31]={
        ["log_name"]="vocane ring", 
        ["id"]=27588, 
        ["name"]="vocane ring", 
        ["count"]=1
    }, 
    [32]={
        ["log_name"]="chirich ring", 
        ["id"]=26181, 
        ["name"]="chirich ring", 
        ["count"]=1
    }, 
    [33]={
        ["log_name"]="chirich ring", 
        ["id"]=26181, 
        ["name"]="chirich ring", 
        ["count"]=1
    }, 
    [34]={
        ["log_name"]="thureous earring", 
        ["id"]=27546, 
        ["name"]="thureous earring", 
        ["count"]=1
    }, 
    [35]={
        ["log_name"]="enlivened ring", 
        ["id"]=28549, 
        ["name"]="enlivened ring", 
        ["count"]=1
    }, 
    [36]={
        ["log_name"]="coatl gorget +1", 
        ["id"]=28363, 
        ["name"]="coatl gorget +1", 
        ["count"]=1
    }, 
    [37]={
        ["log_name"]="friomisi earring", 
        ["id"]=28514, 
        ["name"]="friomisi earring", 
        ["count"]=1
    }
}