-- Generated by the Organizer Library (10/14/17 14:57:57)
return {
    [1]={
        ["log_name"]="goldsmith's smock", 
        ["id"]=11331, 
        ["name"]="goldsmith's smock", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="goldsmith's torque", 
        ["id"]=10950, 
        ["name"]="goldsm. torque", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="jumalik helm", 
        ["count"]=1, 
        ["id"]=25603, 
        ["name"]="jumalik helm", 
        ["augments"]={
            [1]="MND+5", 
            [2]="\"Mag.Atk.Bns.\"+10", 
            [3]="Magic burst dmg.+6%"
        }
    }, 
    [4]={
        ["log_name"]="craftmaster's ring", 
        ["id"]=28586, 
        ["name"]="craftmaster's ring", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="gold moogle belt", 
        ["id"]=13216, 
        ["name"]="gold mog. belt", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="souveran schuhs +1", 
        ["id"]=27375, 
        ["name"]="souveran schuhs +1", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="souveran handschuhs +1", 
        ["id"]=27023, 
        ["name"]="souv. handsch. +1", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="weard mantle", 
        ["id"]=28623, 
        ["name"]="weard mantle", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="staunch tathlum", 
        ["id"]=22278, 
        ["name"]="staunch tathlum", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="rudianos's mantle", 
        ["count"]=1, 
        ["id"]=26252, 
        ["name"]="rudianos's mantle", 
        ["augments"]={
            [1]="HP+60", 
            [2]="Accuracy+20 Attack+20", 
            [3]="Enmity+10"
        }
    }, 
    [11]={
        ["log_name"]="rudianos's mantle", 
        ["count"]=1, 
        ["id"]=26252, 
        ["name"]="rudianos's mantle", 
        ["augments"]={
            [1]="HP+60", 
            [2]="Eva.+20 /Mag. Eva.+20", 
            [3]="HP+10", 
            [4]="\"Fast Cast\"+10"
        }
    }, 
    [12]={
        ["log_name"]="craftkeeper's ring", 
        ["id"]=28585, 
        ["name"]="craftkeeper's ring", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="souveran cuirass", 
        ["id"]=26846, 
        ["name"]="souveran cuirass", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="shaded spectacles", 
        ["id"]=13945, 
        ["name"]="shaded specs.", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="incantor stone", 
        ["id"]=19257, 
        ["name"]="incantor stone", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="ginsen", 
        ["id"]=21371, 
        ["name"]="ginsen", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="creed collar", 
        ["id"]=11595, 
        ["name"]="creed collar", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="carmine cuisses +1", 
        ["id"]=27207, 
        ["name"]="carmine cuisses +1", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="creed earring", 
        ["id"]=11709, 
        ["name"]="creed earring", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="artificer's ring", 
        ["id"]=28587, 
        ["name"]="artificer's ring", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="creed baudrier", 
        ["id"]=11750, 
        ["name"]="creed baudrier", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="souveran diechlings +1", 
        ["id"]=27199, 
        ["name"]="souv. diechlings +1", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="loess barbuta +1", 
        ["id"]=25636, 
        ["name"]="loess barbuta +1", 
        ["count"]=1
    }
}