-- Generated by the Organizer Library (10/14/17 14:57:57)
return {
    [1]={
        ["log_name"]="priwen", 
        ["id"]=28648, 
        ["name"]="priwen", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="homiliary", 
        ["id"]=22268, 
        ["name"]="homiliary", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="reverence surcoat +2", 
        ["id"]=23113, 
        ["name"]="rev. surcoat +2", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="ochain", 
        ["id"]=16193, 
        ["name"]="ochain", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="cizin helm", 
        ["id"]=27768, 
        ["name"]="cizin helm", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="twilight mail", 
        ["id"]=11362, 
        ["name"]="twilight mail", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="caballarius leggings", 
        ["id"]=27340, 
        ["name"]="cab. leggings", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="caballarius breeches +1", 
        ["id"]=27165, 
        ["name"]="cab. breeches +1", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="iron gobbet", 
        ["id"]=19782, 
        ["name"]="iron gobbet", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="yaoyotl helm", 
        ["id"]=27773, 
        ["name"]="yaoyotl helm", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="caballarius surcoat +1", 
        ["id"]=26813, 
        ["name"]="cab. surcoat +1", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="reverence gauntlets +1", 
        ["id"]=27970, 
        ["name"]="rev. gauntlets +1", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="twilight helm", 
        ["id"]=11798, 
        ["name"]="twilight helm", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="shaper's shawl", 
        ["id"]=11009, 
        ["name"]="shaper's shawl", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="caballarius gauntlets +1", 
        ["id"]=26989, 
        ["name"]="cab. gauntlets +1", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="reverence coronet +1", 
        ["id"]=27690, 
        ["name"]="rev. coronet +1", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="aegis", 
        ["id"]=11927, 
        ["name"]="aegis", 
        ["count"]=1
    }
}