-- Generated by the Organizer Library (10/14/17 14:57:57)
return {
    [1]={
        ["log_name"]="emicho gambieras", 
        ["id"]=27469, 
        ["name"]="emicho gambieras", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="founder's gauntlets", 
        ["id"]=28049, 
        ["name"]="founder's gauntlets", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="yorium cuirass", 
        ["id"]=26891, 
        ["name"]="yorium cuirass", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="kaiser diechlings", 
        ["id"]=14283, 
        ["name"]="kaiser diechlings", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="founder's hose", 
        ["id"]=28191, 
        ["name"]="founder's hose", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="founder's greaves", 
        ["id"]=28330, 
        ["name"]="founder's greaves", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="souveran schaller +1", 
        ["id"]=26671, 
        ["name"]="souv. schaller +1", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="yorium barbuta", 
        ["id"]=26733, 
        ["name"]="yorium barbuta", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="valorous mask", 
        ["id"]=25641, 
        ["name"]="valorous mask", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="eschite greaves", 
        ["id"]=27457, 
        ["name"]="eschite greaves", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="founder's breastplate", 
        ["id"]=27910, 
        ["name"]="found. breastplate", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="odyssean greaves", 
        ["id"]=27494, 
        ["name"]="odyssean greaves", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="odyssean cuisses", 
        ["count"]=1, 
        ["id"]=25840, 
        ["name"]="odyssean cuisses", 
        ["augments"]={
            [1]="VIT+6", 
            [2]="\"Dbl.Atk.\"+3", 
            [3]="Phalanx +4", 
            [4]="Mag. Acc.+17 \"Mag.Atk.Bns.\"+17"
        }
    }, 
    [14]={
        ["log_name"]="emicho haubert", 
        ["id"]=25682, 
        ["name"]="emicho haubert", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="eschite gauntlets", 
        ["id"]=27097, 
        ["name"]="eschite gauntlets", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="eschite helm", 
        ["id"]=26791, 
        ["name"]="eschite helm", 
        ["count"]=1
    }
}